name: MC-CTF
version: ${project.version}
main: com.fallenmoons.mcctf.Main
api-version: 1.13
commands:
  clear:
    description: Clears the player's inventory.
    usage: /<command>
  setspawn:
    description: Sets a new world spawn.
    usage: /<command>
  spawn:
    description: Teleports the player to the world spawn.
    usage: /<command>
  startround:
    description: Starts a new round.
    usage: /<command>
  gui:
    description: GUI test.
    usage: /<command>
  jointeam:
    description: Join a team.
    usage: /<command> [team]
  viewteams:
    description: View all players on teams.
    usage: /<command>
  hat:
    description: Gives you a neat hat!
    usage: /<command>
  trail:
    description: Gives you a cool trail.
    usage: /<command> [(to set trail) trail]
  createflag:
    description: Creates a team flag.
    usage: /<command>
  heal:
    description: Heals you!
    usage: /<command>
  feed:
    description: Feeds you!
    usage: /<command>
  randompicker:
    description: Picks a random player.
    usage: /<command>
  world:
    description: Takes you to a whole new world!
    usage: /<command> [worldname]
  gotoinstance:
    description: Takes you to an instance of the game world.
    usage: /<command> [worldname]
  createteamspawn:
    description: Creates a new spawn for the given team at the player's location.
    usage: /<command> [teamname]
  givecustom:
    description: Gives a custom item. Currently only "grappling_hook" is available.
    usage: /<command> [player] [customitem]